name: Build
on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  node-build:
    runs-on: ubuntu-latest
    name: Javascript build
    steps:
    - uses: actions/checkout@master
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Make
      run: make
